networks:
  local_net:  
    driver: bridge
services:
  postgresql:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: findme_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - local_net


  findme_api:
      build:
        context: .
      env_file:
        - .env
      depends_on:
        - postgresql
      ports:
        - "8000:8000"
      networks:
        - local_net
  